LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := amazefilemanager
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := amazefilemanager.apk
LOCAL_OVERRIDES_PACKAGES := CMFileManager
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

